CREATE DATABASE Loja;

USE Loja;

CREATE TABLE Produtos(
	COD_Prod INT NOT NULL,
	Preco_Venda FLOAT NOT NULL,
	Descricao VARCHAR(255),
	Data_Validade DATE NOT NULL,
	Preco_Custo FLOAT NOT NULL,
	Estoque INT,
	COD_Dist INT NOT NULL);

CREATE TABLE Distribuidores(
	COD_Dist INT NOT NULL,
	Nome_Fantasia VARCHAR(100) NOT NULL,
	Razao_Social VARCHAR(100) NOT NULL,
	Telefone VARCHAR(12) NOT NULL,
	Email VARCHAR(100));

CREATE TABLE Clientes(
	COD_Cli INT NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Data_Nasc DATE NOT NULL,
	Endereco VARCHAR(255) NOT NULL,
	Telefone VARCHAR(12) NOT NULL,
	Email VARCHAR(100));

CREATE TABLE Vendas(
	COD_Venda INT NOT NULL,
	Data_Venda VARCHAR(11) NOT NULL,
	Hora_Venda VARCHAR(6) NOT NULL,
	Total_Venda FLOAT NOT NULL,
	COD_Cli INT);

CREATE TABLE Itens_Venda(
	COD_Itens_Venda INT NOT NULL,
	Quantidade INT NOT NULL,
	Sub_Total FLOAT NOT NULL,
	COD_Venda INT,
	COD_Produto INT);

--Execução de PK e FK--
ALTER TABLE Distribuidores 
ADD CONSTRAINT PK_DISTRIBUIDORES PRIMARY KEY(COD_Dist);

ALTER TABLE Produtos 
ADD CONSTRAINT PK_PRODUTOS PRIMARY KEY(COD_Prod),
CONSTRAINT FK_DISTRIBUIDORES FOREIGN KEY(COD_Dist) REFERENCES Distribuidores(COD_Dist);

ALTER TABLE Clientes 
ADD CONSTRAINT PK_CLIENTES PRIMARY KEY(COD_Cli);

ALTER TABLE Vendas 
ADD CONSTRAINT PK_VENDAS PRIMARY KEY(COD_Venda),
CONSTRAINT FK_CLIENTES  FOREIGN KEY(COD_Cli) REFERENCES Clientes(COD_Cli);

ALTER TABLE Itens_Venda 
ADD CONSTRAINT PK_ITENS_VENDA PRIMARY KEY(COD_Itens_Venda),
CONSTRAINT FK_VENDA FOREIGN KEY(COD_Venda) REFERENCES Vendas(COD_Venda),
CONSTRAINT FK_PRODUTO FOREIGN KEY(COD_Produto) REFERENCES Produtos(COD_Prod);